# Generated by Django 4.0.1 on 2022-02-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_auto_20220130_2039"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="last_report_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="send_report",
            field=models.BooleanField(default=False),
        ),
    ]
