# Generated by Django 4.0.1 on 2022-01-25 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="owner",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_date",
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TaskChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        max_length=100,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
        ),
    ]
