# Generated by Django 4.0.1 on 2022-01-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
