# Generated by Django 4.0.2 on 2022-02-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_usersettings_last_report_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskchange",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="tasks.task",
            ),
        ),
    ]
