# Generated by Django 3.2.11 on 2022-01-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_auto_20220131_0731"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="send_report_task",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="send_report_task_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
