# Generated by Django 4.0.2 on 2022-02-10 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_usersettings_last_report_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='report_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
