# Generated by Django 4.0.1 on 2022-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_auto_20220131_2232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="send_report_task_id",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="last_report_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
