# Generated by Django 4.0.2 on 2022-02-10 13:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_taskchange_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="report_time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
