# Generated by Django 4.0.1 on 2022-01-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_unique_task_priority'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_task_priority',
        ),
    ]
