#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput

/usr/local/bin/gunicorn task_manager.wsgi --bind 0.0.0.0:8000 --chdir=/app
